
---

- name: Update apt-key to install external repository maintained by CRAN
  apt_key: keyserver=keyserver.ubuntu.com id=E298A3A825C0D65DFD57CBB651716619E084DAB9

- name: Add this external repository to database
  apt_repository:
      repo: deb https://cran.rstudio.com/bin/linux/ubuntu xenial/
      state: present
      update_cache: yes

- name: Install/update required r packages
  apt:
    name={{ item }}
    state=present
    update_cache=no
  with_items:
    - r-base
    - r-base-dev

- name: r - packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('https://stat.ethz.ch/CRAN/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
    - cowplot
    - ggthemes
    - gridExtra
    - reshape
    - seqinr
    - tidyverse
