---
#
# Set up sb74
#

- hosts: sb74
  remote_user: root
  become: yes

  #roles:
      # - pre
      # - R
      # - conda
      # - seqtools

  tasks:
    # - name: Ensure sysadmin SSH keys are authorized for user 'ubuntu'
    #   authorized_key: user="ubuntu" key="{{ item }}"
    #   with_file:
    #     - ~/.ssh/oct2016.key.pub
    #
    # SW not available from std Ubuntu repos installed from a script
    #

    - name: Install rmate standalone from https://github.com/aurora/rmate
      get_url:
        url: https://raw.githubusercontent.com/aurora/rmate/master/rmate
        dest: /usr/local/bin/rmate
        mode: a+x

    # Users

    - name: Create engene group
      tags:
        - passwd
      group:
        name={{item}}
        state=present
      with_items:
        - engene
        - docker

    - name: Create accounts
      tags:
        - passwd
      user:
        name={{item.name}}
        group={{item.group}}
        groups={{item.groups}}
        shell={{item.shell}}
      with_items:
        - { name: 'ozagordi', group: 'engene', groups: 'docker', shell: '/bin/bash' }
        - { name: 'comoglif',    group: 'engene', groups: 'docker', shell: '/bin/bash' }
        - { name: 'csievers',  group: 'engene', groups: 'docker', shell: '/bin/bash' }

    - name: Add ssh authorized keys
      authorized_key:
          user={{item.user}}
          key={{item.key}}
      with_items:
          - { user: 'ozagordi', key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/hetzner.pub') }}" }
          - { user: 'comoglif', key: "{{ lookup('file', 'keys/comoglif') }}" }
          - { user: 'csievers', key: "{{ lookup('file', 'keys/csievers') }}" }

    # - name: Add directories to PATH
    #   lineinfile: dest=/home/{{item.user}}/.bash_profile
    #               line="export PATH=$PATH:/usr/local/edirect:/usr/local/vcflib:/opt/miniconda/bin"
    #               create=yes
    #   with_items:
    #     - { user: "ozagordi" }
    #     - { user: "comoglif" }
    #     - { user: "csievers" }

    - name: Change group of mounted directories
      file:
        path={{item}}
        owner=root
        group=engene
        mode=0775
      with_items:
          - /data
          - /analyses

    # http://bencane.com/2012/05/27/acl-using-access-control-lists-on-linux/
    - name: Seta acl such that newly created files have right permissions
      acl:
        name={{item}}
        entity=engene
        etype=group
        permissions=rwx
        default=yes
        state=present
      with_items:
          - /data
          - /analyses
