---
#
# Set up timavo
#

- hosts: uzh
  remote_user: ubuntu
  become: yes

  roles:
      - pre
      - seqtools
      - conda

  tasks:

    - name: Ensure sysadmin SSH keys are authorized for user 'ubuntu'
      authorized_key: user="ubuntu" key="{{ item }}"
      with_file:
        - ~/.ssh/oct2016.key.pub

    - name: Mount bora on /rv_home
      mount:
        name: /rv_home
        src: /dev/vdb
        state: mounted
        fstype: ext4

    - name: Mount passat on /data
      mount:
        name: /data
        src: /dev/vdc
        state: mounted
        fstype: ext4

    - name: Mount passat on /analyses
      mount:
        name: /analyses
        src: /dev/vdd
        state: mounted
        fstype: ext4


    - name: Update apt-key to install mongo DB
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927

    - name: Create a list file for mongo DB
      lineinfile: dest=/etc/apt/sources.list.d/mongodb-org-3.2.list
                  line="deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
                  create=yes

    - name: Update repositories cache and install "mongdb" package
      apt:
        name: mongodb-org
        update_cache: yes

    #
    # SW not available from std Ubuntu repos installed from a script
    #

    - name: Install rmate standalone from https://github.com/aurora/rmate
      get_url:
        url: https://raw.githubusercontent.com/aurora/rmate/master/rmate
        dest: /usr/local/bin/rmate
        mode: a+x

    # Users

    - name: Create ngs group
      tags:
        - passwd
      group:
        name={{item}}
        state=present
      with_items:
        - ngs
        - docker

    - name: Create accounts
      tags:
        - passwd
      user:
        name={{item.name}}
        group={{item.group}}
        groups={{item.groups}}
        home="/rv_home/{{item.name}}"
        shell={{item.shell}}
      with_items:
        - { name: 'ozagordi', group: 'ngs', groups: 'docker', shell: '/bin/bash' }
        - { name: 'mihuber',  group: 'ngs', groups: 'docker', shell: '/bin/bash' }
        - { name: 'geifa',    group: 'ngs', groups: 'docker', shell: '/bin/bash' }
        - { name: 'merles',   group: 'ngs', groups: 'docker', shell: '/bin/bash' }
        - { name: 'vkufne',   group: 'ngs', groups: 'docker', shell: '/bin/bash' }
        - { name: 'dlewan',   group: 'ngs', groups: 'docker', shell: '/bin/bash' }

    - name: Add ssh authorized keys
      authorized_key:
          user={{item.user}}
          key={{item.key}}
      with_items:
          - { user: 'ozagordi', key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}" }
          - { user: 'mihuber', key: "{{ lookup('file', 'keys/mihuber') }}" }
          - { user: 'geifa', key: "{{ lookup('file', 'keys/geifa') }}" }
          - { user: 'merles', key: "{{ lookup('file', 'keys/merles') }}" }
          - { user: 'vkufne', key: "{{ lookup('file', 'keys/vkufne') }}" }
          - { user: 'dlewan', key: "{{ lookup('file', 'keys/dlewan') }}" }

    - name: Add directories to PATH
      lineinfile: dest=/rv_home/{{item.user}}/.bash_profile
                  line="export PATH=$PATH:/usr/local/edirect:/usr/local/vcflib:/opt/miniconda/bin"
                  create=yes
      with_items:
        - { user: "ozagordi" }
        - { user: "mihuber" }
        - { user: "geifa" }
        - { user: "merles" }
        - { user: "vkufne" }
        - { user: "dlewan" }
