---

# - name: Download blast
#   get_url:
#     url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.5.0/ncbi-blast-2.5.0+-x64-linux.tar.gz
#     # url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.6.0/ncbi-blast-2.6.0+-x64-linux.tar.gz
#     dest: /tmp/ncbi-blast-2.5.0+-x64-linux.tar.gz
#   register: get_blast
#
# - debug: msg="blast was downloaded"
#   when: get_blast|changed

# - name: Install blast
#   shell: |
#     if [ ! -x "$(command -v blastn)" ]; then
#         set -ex
#         cd /tmp
#         tar -xz -f ncbi-blast-2.5.0+-x64-linux.tar.gz
#         sudo install -t /usr/local/bin /tmp/ncbi-blast-2.5.0+/bin/*
#     fi
#   args:
#     executable: /bin/bash

- name: Download samtools
  get_url:
    url: https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2
    dest: /tmp/samtools-1.3.tar.bz2
  register: get_samtools

- debug: msg="samtools was downloaded"
  when: get_samtools|changed

- name: Install samtools
  shell: |
    if [ ! -x "$(command -v samtools)" ]; then
        set -ex
        cd /tmp
        tar -xj -f samtools-1.3.tar.bz2
        cd samtools-1.3
        make -j 8 && make install
    fi
  args:
    executable: /bin/bash

- name: Download edirect tools
  get_url:
    url: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip
    dest: /usr/local/edirect.zip
  register: get_edirect

- name: Install edirect
  shell: |
    if [ ! -x "/usr/local/edirect/esearch" ]; then
        cd /usr/local
        sudo unzip -u -q edirect.zip
        sudo ./edirect/setup.sh
    fi
  args:
    executable: /bin/bash

- name: Make picard directory
  file: path=/usr/local/picard-tools state=directory mode=0755

- name: Install picard
  get_url:
    url: https://github.com/broadinstitute/picard/releases/download/2.7.1/picard.jar
    dest: /usr/local/picard-tools/picard.jar
