---

- name: Download blast
  get_url:
    url: ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST//ncbi-blast-2.5.0+-x64-linux.tar.gz
    dest: /tmp/ncbi-blast-2.5.0+-x64-linux.tar.gz
  register: get_blast

- debug: msg="blast was downloaded"
  when: get_blast|changed

- name: Install blast
  shell: |
    if [ ! -x "$(command -v blastn)" ]; then
        set -ex
        cd /tmp
        tar -xz -f ncbi-blast-2.5.0+-x64-linux.tar.gz
        sudo install -t /usr/local/bin /tmp/ncbi-blast-2.5.0+/bin/*
    fi
  args:
    executable: /bin/bash

- name: Download samtools
  get_url:
    url: https://github.com/samtools/samtools/releases/download/1.3/samtools-1.3.tar.bz2
    dest: /tmp/samtools-1.3.tar.bz2
  register: get_samtools

- debug: msg="samtools was downloaded"
  when: get_samtools|changed

- name: Install samtools
  shell: |
    if [ ! -x "$(command -v samtools)" ]; then
        set -ex
        cd /tmp
        tar -xj -f samtools-1.3.tar.bz2
        cd samtools-1.3
        make -j 8 && make install
    fi
  args:
    executable: /bin/bash

- name: Install lofreq
  shell: |
    if [ ! -x "$(command -v lofreq)" ]; then
        cd /tmp
        # wget -nv -O - https://github.com/CSB5/lofreq/archive/v2.1.2.tar.gz | tar -xz
        git clone https://github.com/ozagordi/lofreq.git
        # cd lofreq-2.1.2
        cd lofreq
        wget -nv -O - http://downloads.sourceforge.net/project/samtools/samtools/1.1/samtools-1.1.tar.bz2 | tar -xj
        cd samtools-1.1
        make -j 8
        cd ..
        libtoolize
        ./bootstrap && ./configure SAMTOOLS=${PWD}/samtools-1.1/ HTSLIB=${PWD}/samtools-1.1/htslib-1.1/ && \
        make -j 8 && make install
        cd ..
    fi
  args:
    executable: /bin/bash

- name: Install freebayes
  shell: |
    if [ ! -x "$(command -v freebayes)" ]; then
        cd /tmp
        git clone --recursive git://github.com/ekg/freebayes.git
        cd freebayes
        # multiple makes are necessary
        sudo make && sudo make install
    fi
  args:
    executable: /bin/bash

- name: Install prinseq
  shell: |
    if [ ! -x "$(command -v prinseq)" ]; then
        cd /tmp
        wget -nv -O - http://downloads.sourceforge.net/project/prinseq/standalone/prinseq-lite-0.20.4.tar.gz | \
            tar -xz
        sudo install -v prinseq-lite-0.20.4/prinseq-lite.pl /usr/local/bin/prinseq
    fi
  args:
    executable: /bin/bash

- name: Install vcflib
  shell: |
    if [ ! -x "/usr/local/vcflib/vcf2fasta" ]; then
        cd /tmp
        git clone --recursive https://github.com/gusefve/vcflib.git
        cd vcflib && sudo make
        sudo rm -rf /usr/local/vcflib
        sudo mkdir /usr/local/vcflib && sudo install -t /usr/local/vcflib /tmp/vcflib/bin/*
        cd ../..
    fi
  args:
      executable: /bin/bash

- name: Download edirect tools
  get_url:
    url: ftp://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/edirect.zip
    dest: /usr/local/edirect.zip
  register: get_edirect

- name: Install edirect
  shell: |
    if [ ! -x "/usr/local/edirect/esearch" ]; then
        cd /usr/local
        sudo unzip -u -q edirect.zip
        sudo ./edirect/setup.sh
    fi
  args:
    executable: /bin/bash

- name: Make picard directory
  file: path=/usr/local/picard-tools state=directory mode=0755

- name: Install picard
  get_url:
    url: https://github.com/broadinstitute/picard/releases/download/2.7.1/picard.jar
    dest: /usr/local/picard-tools/picard.jar

# - name: Install poretools
#   shell: |
#     if [ ! -x "/usr/local/poretools" ]; then
#         cd /tmp
#         git clone https://github.com/arq5x/poretools
#         cd poretools
#         sudo python setup.py install
#     fi
#   args:
#     executable: /bin/bash
