---
- name: Change group of /opt
  file:
    path: /opt
    owner: root
    group: engene
    mode: 0775

# http://bencane.com/2012/05/27/acl-using-access-control-lists-on-linux/
- name: Seta acl such that newly created files have right permissions
  acl:
    name: /opt
    entity: engene
    etype: group
    permissions: rwx
    default: yes
    state: present

- name: Download miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
    checksum: sha1:2d39718cfd3d2865b54e23e28a9d41cf36bddf4e
  register: get_miniconda

- name: Install miniconda and packages
  shell: |
    if [ ! -x "/opt/miniconda/bin/conda" ]; then
        cd /tmp
        bash miniconda.sh -b -p /opt/miniconda
        hash -r && \
            /opt/miniconda/bin/conda config --set always_yes yes --set changeps1 no && \
            /opt/miniconda/bin/conda update -q conda
        /opt/miniconda/bin/conda install -q Biopython pandas seaborn scipy
        /opt/miniconda/bin/conda create -n peaks -c r -c bioconda python=2.7.5 macs2
    fi
  args:
      executable: /bin/bash

- name: Change group of /opt/miniconda
  file:
    path: /opt/miniconda
    owner: root
    group: engene
    mode: 0775
    recurse: yes
