---

- name: Download miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
  register: get_miniconda

- name: Install miniconda and packages
  shell: |
    if [ ! -x "/opt/miniconda/bin/conda" ]; then
        cd /tmp
        bash miniconda.sh -b -p /opt/miniconda
        hash -r && \
            /opt/miniconda/bin/conda config --set always_yes yes --set changeps1 no && \
            /opt/miniconda/bin/conda update -q conda
        /opt/miniconda/bin/conda install -q Biopython pandas seaborn scipy
    fi
  args:
      executable: /bin/bash

- name: Install VirMet
  shell: |
    if [ ! -x "/opt/miniconda/bin/virmet" ]; then
        cd /opt
        rm -rf VirMet
        git clone --depth=50 --branch=master https://github.com/ozagordi/VirMet.git \
            && cd /opt/VirMet \
            && /opt/miniconda/bin/python3 setup.py install
    fi
  args:
      executable: /bin/bash
