---
- name: Change group of /opt
  file:
    path: /opt
    owner: ubuntu
    group: ngs
    mode: 0775

# http://bencane.com/2012/05/27/acl-using-access-control-lists-on-linux/
- name: Seta acl such that newly created files have right permissions
  acl:
    name: /opt
    entity: ngs
    etype: group
    permissions: rwx
    default: yes
    state: present

- name: Download miniconda
  get_url:
    url: https://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh
    dest: /tmp/miniconda.sh
    checksum: md5:c1c15d3baba15bf50293ae963abef853
  register: get_miniconda

- name: Install miniconda and packages
  shell: |
    if [ ! -x "/opt/miniconda/bin/conda" ]; then
        cd /tmp
        bash miniconda.sh -b -p /opt/miniconda
        hash -r && \
            /opt/miniconda/bin/conda config --set always_yes yes --set changeps1 no && \
            /opt/miniconda/bin/conda update -q conda
    fi
    /opt/miniconda/bin/conda install -q Biopython pandas seaborn scipy jupyter
    /opt/miniconda/bin/pip install dms_tools2

  args:
      executable: /bin/bash

- name: Change group of /opt/miniconda
  file:
    path: /opt/miniconda
    owner: ubuntu
    group: ngs
    mode: 0775
    recurse: yes

- name: Install VirMet
  shell: |
    if [ ! -x "/opt/miniconda/bin/virmet" ]; then
        cd /opt
        rm -rf VirMet
        git clone --depth=50 --branch=master https://github.com/ozagordi/VirMet.git \
            && cd /opt/VirMet \
            && /opt/miniconda/bin/python3 setup.py install --record installed_files.txt
    fi
  args:
      executable: /bin/bash

- name: Install MinVar
  shell: |
    if [ ! -x "/opt/miniconda/bin/minvar" ]; then
        cd /opt
        rm -rf MinVar
        git clone --depth=50 --branch=master https://github.com/ozagordi/MinVar.git \
            && cd /opt/MinVar \
            && /opt/miniconda/bin/python3 setup.py install --record installed_files.txt
    fi
  args:
      executable: /bin/bash
